[package]
name = "robust_tokio_modbus"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["macros", "rt"] }
tokio-modbus = "0.15.0"
tokio-retry = "0.3.0"
tracing = "0.1.40"
